#!/usr/bin/env bash
# script that transfers a file from our client to a server

if [ $# == 4 ]
then
	scp -o "StrictHostKeyChecking=no" -i "$1" "$2"@"$3":~/ "$4"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
