#!/usr/bin/env bash
# takes ping as an argument and PING it
# display a usage message if no argument passed
p="$1"
if [ "$p" ];
then
    ping -c 5 "$p"
else
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi