#!/usr/bin/env bash
# script to diplay contents of a file
IFS=':'
file='/etc/passwd'

while read -r line;
do
    part=($line)

    user=${part[0]} # username
    psswd=${part[1]} #password
    uid=${part[2]} #user id
    grop=${part[3]} # group id
    uinfo=${part[4]} # user information
    hom=${part[5]} # home directory
    CSH=${part[6]} # command/shell

    echo "The user $user is part of the $grop gang, lives in $hom and rides $CSH. $uid's place is protected by the passcode $psswd, more info about the user here: $uinfo"

done < "$file"