#!/usr/bin/env bash
# script to diplay contents of a file
file="/etc/passwd"

while IFS= read -r line;
do
    user=$(echo "$line" | cut -d ':' -f1)
    psswd=$(echo "$line" | cut -d ':' -f2)
    uid=$(echo "$line" | cut -d ':' -f3)
    grop=$(echo "$line" | cut -d ':' -f3)
    uinfo=$(echo "$line" | cut -d ':' -f5)
    hom=$(echo "$line" | cut -d ':' -f6)
    CSH=$(echo "$line" | cut -d ':' -f7)

    echo "The user $user is part of the $grop gang, lives in $hom and rides $CSH. $uid's place is protected by the passcode $psswd, more info about the user here: $uinfo"
done < "$file"