#!/usr/bin/env bash
# script to diplay contents of a file
IFS=':'
file='/etc/passwd'

while IFS= read -r line;
do
    user=$(echo "$line" | cut -d ':' -f1) # username
    psswd=$(echo "$line" | cut -d ':' -f2) #password
    uid=$(echo "$line" | cut -d ':' -f3) #user id
    grop=$(echo "$line" | cut -d ':' -f3) # group id
    uinfo=$(echo "$line" | cut -d ':' -f5) # user information
    hom=$(echo "$line" | cut -d ':' -f6) # home directory
    CSH=$(echo "$line" | cut -d ':' -f7) # command/shell

    echo "The user $user is part of the $grop gang, lives in $hom and rides $CSH. $uid's place is protected by the passcode $psswd, more info about the user here: $uinfo"

done < "$file"