#!/usr/bin/env bash
#Bash script that configures an Ubuntu server
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/host_loc
sed -i s/127.0.0.1/127.0.0.1/ > ~/host_loc
echo "8.8.8.8 facebook.com" >> ~/hot_loc
cp -f ~/host_loc /etc/hosts